/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CompteurImport } from './routes/compteur'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CompteurRoute = CompteurImport.update({
  id: '/compteur',
  path: '/compteur',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/compteur': {
      id: '/compteur'
      path: '/compteur'
      fullPath: '/compteur'
      preLoaderRoute: typeof CompteurImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compteur': typeof CompteurRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compteur': typeof CompteurRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/compteur': typeof CompteurRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compteur'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compteur'
  id: '__root__' | '/' | '/compteur'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompteurRoute: typeof CompteurRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompteurRoute: CompteurRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/compteur"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/compteur": {
      "filePath": "compteur.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
